server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sscm?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true      #设置驼峰命名规则自动转换

jwt:
  header: Authorization  #JWT存储的请求头
  secret: xsgSecret #JWT加解密使用的密钥
  expiration: 259200000  #JWT的超期限时间毫秒为单位(这里表示三天过期3600000L * 24 * 3 = 259200000)
  head: Bearer    #JWT负载中拿到开头